### ISSUE TITLE
Use Case Comments 2/20

### ISSUE THREAD

**Issue by germonprez** [amizar1/ISQA3420#12]
UC 1 -- looks good 

UC 2 
1) The corporate developer is not a stakeholder in this UC

UC 3
1) Same as UC2
2) Check your grammar a bit.

**Comment by amizar1** [comment]
## Use case 01

**Title:** Determine License and Vulnerability Result

**Primary Actor:** Corporate Developer

**Goal in Context:** The Corporate developer is able to determine the license and vulnerability result from the provided software package

**Stakeholders:**
- Corporate Developer: To provide the relevant software package result
- Corporate Manager: To receive the correct license and vulnerability result to apply in the software package

**Precondition:**
- Relevant software package information provided
- Database created for storing License and vulnerability result
- Reliable internet connection

**Main Success Scenario:** The Corporate developer receive the correct license and vulnerability result so other can make the proper decision.

**Failed End Conditions:** Corporate developer does not receive the correct license and vulnerability result so other cannot make project decision. 

**Trigger:** The Corporate developer sends the software package to scan for license and vulnerability.
<br><br>


## Use case 02

**Title:** Apply new policy to the software package

**Primary Actor:** Corporate Manager

**Goal in Context:** The Corporate manager is able to apply the new policy to the software package

**Stakeholders:**
- Corporate Manager: To apply the correct policy to the software package

**Precondition:**
- Relevant software package information provided
- Correct software license and vulnerability result provided
- Reliable internet connection

**Main Success Scenario:** The Corporate manager apply correct policy to the software package and receive correct policy information.

**Failed End Conditions:**
- Corporate manager does not apply correct policy to the software package
- Corporate developer does not receive correct policy information of the software package

**Trigger:** The Corporate manager create new policy for the software package or send existing policy to edit or update.
<br><br>


## Use case 03

**Title:** Edit or Update a policy to software package

**Primary Actor:** Corporate Manager

**Goal in Context:** The Corporate manager is able to edit or update the policy to the software package

**Stakeholders:** 
- Corporate Manager: To edit or update the policy correctly to the software package

**Precondition:**
- Relevant software package information provided
- Correct software license and vulnerability result provided
- Reliable internet connection

**Main Success Scenario:** The Corporate manager edit or update the policy correctly to software package and receive correct policy information.

**Failed End Conditions:**
- Corporate manager does not edit or update correct policy to the software package
- Corporate developer does not receive correct policy information of the software package

**Trigger:** The Corporate manager create new policy for the software package or send existing policy to edit or update.

**Comment by amizar1** [comment]
Updated Use cases
