### ISSUE TITLE
DFD Comment 2/20

### ISSUE THREAD

**Issue by germonprez** [amizar1/ISQA3420#13]
1) The Developer does not request policy information (and entities don't talk to entities)
2) The Dev should be able to do a License and Vulnerability Info Request (like the manager) 
3) Leaving the Edit Process, where is Policy Info coming from? I don't see how this is made.

**Comment by amizar1** [comment]
![image](https://cloud.githubusercontent.com/assets/25205721/23137598/6d51a616-f768-11e6-8ac8-317c74cafcee.png)

**Comment by amizar1** [comment]
Updated my DFD diagram
