### ISSUE TITLE
DFD Comments 2/20

### ISSUE THREAD

**Issue by germonprez** [amizar1/ISQA3420#14]
1) Arrows are pointing the wrong direction: 
<img width="157" alt="screen shot 2017-02-20 at 12 53 30 pm" src="https://cloud.githubusercontent.com/assets/656208/23138223/aa0908d0-f76b-11e6-88e1-29fa8160ffcc.png">

That's it. Looks good

**Comment by amizar1** [comment]
![image](https://cloud.githubusercontent.com/assets/25205721/23146265/d2ab1038-f79a-11e6-8576-5ae452d8efc4.png)

**Comment by amizar1** [comment]
Updated the DFD diagram
