### ISSUE TITLE
DFD Image into md file

### ISSUE THREAD

**Issue by germonprez** [amizar1/ISQA3420#4]
Could you edit your DFD.md file to have this single line: 

![image](https://cloud.githubusercontent.com/assets/25205721/22362629/b54887ca-e429-11e6-916a-f4fb6785636e.png)

This should get the image directly into your DFD.md. The way that I did this is that I simply copied the link from your issue. Right click, copy image address.

**Comment by amizar1** [comment]
![image](https://cloud.githubusercontent.com/assets/25205721/22362629/b54887ca-e429-11e6-916a-f4fb6785636e.png)
