### ISSUE TITLE
DFD Issue Feb 1

### ISSUE THREAD

**Issue by germonprez** [amizar1/ISQA3420#7]
This is looking good. 

Minor point: 

1) Check OSS Components and Scan Software can be combined as a single process. 

The Result will then go to the developer and the DB (as you have). 

MG

**Comment by amizar1** [comment]
![image](https://cloud.githubusercontent.com/assets/25205721/22607550/fafd71c8-ea1d-11e6-9626-0319ef33a7a2.png)

**Comment by amizar1** [comment]
Updated the DFD diagram as per your comment.
